[package]
name = "ndk-examples"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"
publish = false

[target.'cfg(target_os = "android")'.dependencies]
anyhow = "1.0"
ndk-glue = { path = "../ndk-glue" }
ndk = { path = "../ndk", features = ["trace", "camera", "media"] }
jni = "0.17"

[[example]]
name = "hello_world"
crate-type = ["cdylib"]

[[example]]
name = "jni_audio"
crate-type = ["cdylib"]

[[example]]
name = "camera"
crate-type = ["cdylib"]

[[package.metadata.android.permission]]
name = "android.permission.CAMERA"

[[package.metadata.android.permission]]
name = "android.permission.WRITE_EXTERNAL_STORAGE"
